# Generated by Django 4.2.16 on 2024-11-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_image_userapplication_ticket_eventimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApplication',
        ),
    ]
